---
- name: Настройка сервера Debian 12
  hosts: localhost  # Выполнение на локальном устройстве
  become: yes  # Использовать sudo для выполнения задач
  tasks:
    - name: Обновление пакетов
      apt:
        update_cache: yes
        upgrade: dist

    - name: Установка nginx
      apt:
        name: nginx
        state: present

    - name: Установка curl
      apt:
        name: curl
        state: present

    - name: Установка git
      apt:
        name: git
        state: present

    - name: Установка Node.js версии 22 через NodeSource
      shell: |
        curl -fsSL https://deb.nodesource.com/setup_22.x | bash -
        apt install -y nodejs

    - name: Клонирование репозитория
      git:
        repo: https://github.com/zzz01t/IthubProject
        dest: /var/www/IthubProject
        version: v4
        single_branch: yes

    - name: Настройка конфигурации nginx
      copy:
        dest: /etc/nginx/sites-available/ithubproject
        content: |
          server {
              listen 80;
              server_name localhost;  # Замените на ваш домен или IP-адрес

              root /var/www/IthubProject/public;  # Путь к публичной директории проекта
              index Привет\!.html Привет!.html index.html index.htm;

              location / {
                  try_files $uri $uri/ =404;
                  proxy_pass http://localhost:8080;  # Проксирование на ваше Node.js приложение
                  proxy_http_version 1.1;
                  proxy_set_header Upgrade $http_upgrade;
                  proxy_set_header Connection 'upgrade';
                  proxy_set_header Host $host;
                  proxy_cache_bypass $http_upgrade;
              }
          }

    - name: Создание символической ссылки для конфигурации nginx
      file:
        src: /etc/nginx/sites-available/ithubproject
        dest: /etc/nginx/sites-enabled/ithubproject
        state: link

    - name: Проверка конфигурации nginx
      command: nginx -t

    - name: Перезапуск nginx
      service:
        name: nginx
        state: restarted

    - name: Установка необходимых пакетов
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Установка Docker
      apt:
        name: docker.io
        state: present

    - name: Запуск и включение Docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: Запуск контейнера с Node.js
      docker_container:
        name: ithubproject
        image: node:22
        state: started
        restart_policy: always
        volumes:
          - /var/www/IthubProject:/usr/src/app
        working_dir: /usr/src/app
        command: npx quartz build --serve
        ports:
          - "8080:8080"
